name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkstyle
        run: make check_fmt
 
      - name: Test
        run: make test
